### ISSUE TITLE
/skin command broken?

### ISSUE THREAD

**Issue by Warrior-15** [k0nker/DMZCraft-Issues#4]
Doing the command "/skin update" doesn't update the player's skin to what it should be

"/skin off" sets the player's skin to default, but "/skin update" grabs an old copy of the player's skin and not (one of) the most recent skin(s)

**Comment by k0nker** [comment]
This is part of CMI. The reason that update isn't always accurate is that there is a delay between when you update your skin and when Mojang pushes that update to the public facing API that plugins and websites are able to pull from.
