### ISSUE TITLE
New backpack noise

### ISSUE THREAD

**Issue by MoonfirePDX** [k0nker/DMZCraft-Issues#7]
**In-Game Name**
MoonfirePDX

**Describe the bug**
With the addition to everyone's inventory of a new backpack access object, we also got a new backpack opening noise. The sound choice itself is fine, but the volume it plays at is far louder than everything else.

**To Reproduce**
1. Open backpack
2. Hear loud barrel noise
3. Open barrel for comparison
4. Notice difference

**Expected behavior**
A sound at the same volume as other sounds

**Location (please complete the following information):**
 - World: Survival
 - Location: Yes
 
**Additional context**
<3

**Screenshots**
Only if you experience synesthesia

**Comment by AWDoBaun** [comment]
Odd thought regarding this: My initial reaction to this issue is that it seems to me that the sound is being played on your head instead of in the world a few blocks away. Now I want to test how loud the barrel open noise is when your head is inside a barrel ( if that's possible )

**Comment by k0nker** [comment]
Turned off the sound for backpacks.
